(async()=>{'use strict';
let lastSeasonDate='';const G=window.GEO, O=window.OUTER_GEO, M=window.MID_GEO, el=id=>document.getElementById(id), originE=G.eMin, originN=G.nMax, width=(G.cols-1)*G.step, depth=(G.rows-1)*G.step, outerWidth=(O.cols-1)*O.step, outerDepth=(O.rows-1)*O.step;
const preference=(key)=>{try{return localStorage.getItem(key)==='1'}catch{return false}};let renderLight=preference('niinimaki-light-render'),dataSaver=preference('niinimaki-data-saver');const params=new URLSearchParams(location.search);if(params.has('light'))renderLight=params.get('light')==='1';if(params.has('data'))dataSaver=params.get('data')==='1';const savePreference=(key,value)=>{try{localStorage.setItem(key,value?'1':'0')}catch{}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const local=(e,n)=>new THREE.Vector3(e-originE,0,originN-n);
function sampleHeight(D,e,n){const x=clamp((e-D.eMin)/D.step,0,D.cols-1.00001),y=clamp((D.nMax-n)/D.step,0,D.rows-1.00001),i=Math.floor(x),j=Math.floor(y),u=x-i,v=y-j,k=j*D.cols+i,h=D.heights;return (h[k]*(1-u)+h[k+1]*u)*(1-v)+(h[k+D.cols]*(1-u)+h[k+D.cols+1]*u)*v}
function rawHeight(e,n){if(e>=G.eMin&&e<=G.eMin+width&&n<=G.nMax&&n>=G.nMax-depth)return sampleHeight(G,e,n);const base=sampleHeight(M&&e>=M.eMin&&e<=M.eMin+(M.cols-1)*M.step&&n<=M.nMax&&n>=M.nMax-(M.rows-1)*M.step?M:O,e,n),ce=clamp(e,G.eMin,G.eMin+width),cn=clamp(n,G.nMax-depth,G.nMax),distance=Math.hypot(e-ce,n-cn);return base+(sampleHeight(G,ce,cn)-base)*clamp(1-distance/1500,0,1)}
const hydro=window.HYDROLOGY_MESH,{SurfaceIndex}=window.HYDRO_SURFACES;
async function unpackFrom(source,name,Type){let stream;if(source[name+'Url']){const response=await fetch(source[name+'Url']);if(!response.ok)throw new Error('Maastoaineiston lataus epäonnistui: '+response.status);stream=response.body}else{const bytes=Uint8Array.from(atob(source[name]),c=>c.charCodeAt(0));stream=new Blob([bytes]).stream()}return new Type(await new Response(stream.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer())}
const unpack=(name,Type)=>unpackFrom(hydro,name,Type);
const [groundPositions,groundIndices,waterPositions,waterIndices]=await Promise.all([unpack('positions',Float32Array),unpack('indices',Uint32Array),unpack('waterPositions',Float32Array),unpack('waterIndices',Uint32Array)]);
const D25=window.MID25_GEO,regional25=await unpackFrom(D25,'decimetres',Int16Array);
function fineHeight(e,n){const precise=mml.sampleFine(e,n);if(Number.isFinite(precise))return precise;const overview=mml.sampleOverview(e,n);if(Number.isFinite(overview))return overview;const x=clamp((e-D25.eMin)/D25.step,0,D25.cols-1.00001),y=clamp((D25.nMax-n)/D25.step,0,D25.rows-1.00001),i=Math.floor(x),j=Math.floor(y),u=x-i,v=y-j,k=j*D25.cols+i;return ((regional25[k]*(1-u)+regional25[k+1]*u)*(1-v)+(regional25[k+D25.cols]*(1-u)+regional25[k+D25.cols+1]*u)*v)/10}
const waterSurfaceIndex=new SurfaceIndex(waterPositions,waterIndices),mml=window.MML_DEM,mmlReady=await mml.ready;
if(mmlReady){
 const levelByOld=new Map(),cover=window.LANDCOVER;
 for(const body of cover.bodies){const area=body.outer,values=[];for(let j=1;j<=5;j++)for(let i=1;i<=5;i++){const e=area.e0+(area.e1-area.e0)*i/6,n=area.n0+(area.n1-area.n0)*j/6;if(!cover.inside(area,e,n)||body.holes.some(h=>cover.inside(h,e,n)))continue;const value=mml.sampleOverview(e,n);if(Number.isFinite(value))values.push(value)}
  if(!values.length){for(const [e,n] of area.points){const value=mml.sampleOverview(e,n);if(Number.isFinite(value)){values.push(value);break}}}
  if(values.length){values.sort((a,b)=>a-b);const level=values[Math.floor(values.length/2)];levelByOld.set(Math.round(body.surface*1000),level);body.surface=level}
 }
 const mappedWater=(old,e,n)=>levelByOld.get(Math.round(old*1000))??mml.sampleOverview(e,n);
 let adjusted=0;for(let k=0;k<groundPositions.length;k+=3){const x=groundPositions[k],z=groundPositions[k+2],e=originE+x,n=originN-z,dem=mml.sampleOverview(e,n);if(!Number.isFinite(dem))continue;const oldWater=waterSurfaceIndex.sample(x,z);if(Number.isFinite(oldWater)){const level=mappedWater(oldWater,e,n);if(Number.isFinite(level))groundPositions[k+1]=level-.15}
  else groundPositions[k+1]=dem;adjusted++}
 for(let k=0;k<waterPositions.length;k+=3){const e=originE+waterPositions[k],n=originN-waterPositions[k+2],level=mappedWater(waterPositions[k+1],e,n);if(Number.isFinite(level))waterPositions[k+1]=level}
 console.info('MML KM2 -korkeuteen sovitettuja maastopisteitä',adjusted)
}
const groundSurface=new SurfaceIndex(groundPositions,groundIndices);
const localGroundSurfaces=new Map();
function height(e,n){const x=e-originE,z=originN-n,key=Math.floor(x/4000)+','+Math.floor(z/4000),fine=localGroundSurfaces.get(key)?.sample(x,z);if(Number.isFinite(fine))return fine;const h=groundSurface.sample(x,z);return Number.isFinite(h)?h:rawHeight(e,n)}
window.LANDCOVER.waterSurface=(e,n)=>waterSurfaceIndex.sample(e-originE,originN-n);
window.LANDCOVER.inWater=(e,n)=>Number.isFinite(window.LANDCOVER.waterSurface(e,n));
function walkingHeight(e,n){const ground=height(e,n),water=window.LANDCOVER.waterSurface(e,n);return Math.max(ground,Number.isFinite(water)?water:-Infinity)+viewerHeight}

const observer={e:343424,n:6759709};let windDegrees=270;let mode='ground',selectMode=false,playing=false,timeMinutes=720,yaw=0,pitch=0,viewerHeight=1.7,dragging=false,lastX=0,lastY=0,downX=0,downY=0,downTime=0;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8fb8c7);scene.fog=new THREE.FogExp2(0x9eb6ba,.000018);
const camera=new THREE.PerspectiveCamera(54,1,.2,160000);camera.position.set(4600,1550,6700);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,renderLight?1:1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.BasicShadowMap;renderer.outputEncoding=THREE.sRGBEncoding;el('scene').appendChild(renderer.domElement);
const controls=new THREE.OrbitControls(camera,renderer.domElement);controls.target.set(5200,145,3900);controls.enableDamping=true;controls.dampingFactor=.07;controls.maxPolarAngle=Math.PI/2.03;controls.minDistance=250;controls.maxDistance=80000;controls.update();
const hemi=new THREE.HemisphereLight(0xe3f5ff,0x405147,.28);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff5db,1.25);sun.castShadow=true;sun.shadow.mapSize.set(renderLight?1024:3072,renderLight?1024:3072);sun.shadow.camera.left=-6200;sun.shadow.camera.right=6200;sun.shadow.camera.top=5400;sun.shadow.camera.bottom=-5400;sun.shadow.camera.near=100;sun.shadow.camera.far=16000;sun.shadow.bias=-.0004;sun.shadow.normalBias=.4;scene.add(sun);scene.add(sun.target);
const canopyMask=Uint8Array.from(atob(window.CANOPY.heights),ch=>ch.charCodeAt(0)),colors=new Float32Array(groundPositions.length),c=new THREE.Color();
const palette=[[.64,.49,.11],[.57,.47,.15],[.66,.54,.18],[.58,.44,.09],[.61,.55,.21],[.55,.50,.13],[.67,.50,.16],[.60,.52,.12]];
for(let k=0;k<groundPositions.length;k+=3){const e=originE+groundPositions[k],n=originN-groundPositions[k+2],h=groundPositions[k+1],cover=window.LANDCOVER,fieldIndex=cover.fieldAt(e,n),canopy=window.CANOPY,ci=Math.floor((e-canopy.eMin)/canopy.step),cj=Math.floor((canopy.nMax-n)/canopy.step),forest=ci>=0&&ci<canopy.cols&&cj>=0&&cj<canopy.rows&&canopyMask[cj*canopy.cols+ci]>=5,t=clamp((h-105)/90,0,1);
 if(fieldIndex>=0){const p=palette[cover.fields[fieldIndex].shade];c.setRGB(p[0]+t*.06,p[1]+t*.05,p[2]+t*.02)}else if(forest)c.setRGB(.13+t*.07,.25+t*.10,.15+t*.05);else c.setRGB(.36+t*.12,.44+t*.11,.28+t*.06);
 colors[k]=c.r;colors[k+1]=c.g;colors[k+2]=c.b;
}
const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(groundPositions,3));geo.setAttribute('color',new THREE.BufferAttribute(colors,3));geo.setIndex(new THREE.BufferAttribute(groundIndices,1));geo.computeVertexNormals();
const summerColors=colors.slice();const terrainMaterial=new THREE.MeshLambertMaterial({vertexColors:true});
// Lambert already samples the turbine shadow map. Reuse that result to darken
// the terrain in the same pass instead of drawing a second terrain mesh.
terrainMaterial.onBeforeCompile=shader=>{
 const shadowLine='reflectedLight.directDiffuse *= BRDF_Diffuse_Lambert( diffuseColor.rgb ) * getShadowMask();';
 const outputLine='vec3 outgoingLight = reflectedLight.directDiffuse + reflectedLight.indirectDiffuse + totalEmissiveRadiance;';
 if(!shader.fragmentShader.includes(shadowLine)||!shader.fragmentShader.includes(outputLine)){console.warn('Maastovarjon shader-rakenne muuttui');return}
 shader.fragmentShader=shader.fragmentShader.replace(shadowLine,'float terrainShadow = getShadowMask();\n\treflectedLight.directDiffuse *= BRDF_Diffuse_Lambert( diffuseColor.rgb ) * terrainShadow;').replace(outputLine,outputLine+'\n\toutgoingLight *= mix(0.02, 1.0, terrainShadow);');
};
const terrain=new THREE.Mesh(geo,terrainMaterial);terrain.name='Yhtenäinen maasto';terrain.visible=false;scene.add(terrain);
let terrainSnow=0,terrainSpring=1;function colorDetailTile(tile){if(!tile.fineMesh)return;const attr=tile.fineMesh.geometry.attributes.color,a=attr.array;for(let k=0;k<a.length;k+=3){a[k]=tile.summerColors[k]*(1-terrainSnow)+.88*terrainSnow;a[k+1]=(tile.summerColors[k+1]*(1-terrainSnow)+.91*terrainSnow)*(terrainSnow<1?.78+.22*terrainSpring:1);a[k+2]=tile.summerColors[k+2]*(1-terrainSnow)+.89*terrainSnow}attr.needsUpdate=true}
// The collision/raycast surface stays continuous; rendering uses culled tiles
// sharing its exact vertex/color buffers, with no second floating ground layer.
const terrainTiles=new Map();for(let k=0;k<groundIndices.length;k+=3){const ia=groundIndices[k]*3,ib=groundIndices[k+1]*3,ic=groundIndices[k+2]*3,x=(groundPositions[ia]+groundPositions[ib]+groundPositions[ic])/3,z=(groundPositions[ia+2]+groundPositions[ib+2]+groundPositions[ic+2])/3,key=Math.floor(x/4000)+','+Math.floor(z/4000);let tile=terrainTiles.get(key);if(!tile)terrainTiles.set(key,tile={indices:[],box:new THREE.Box3()});for(let q=0;q<3;q++){const id=groundIndices[k+q];tile.indices.push(id);tile.box.expandByPoint(new THREE.Vector3().fromArray(groundPositions,id*3))}}
for(const [key,tile] of terrainTiles){const g=new THREE.BufferGeometry();for(const name of ['position','color','normal'])g.setAttribute(name,geo.attributes[name]);g.setIndex(tile.indices);g.boundingSphere=tile.box.getBoundingSphere(new THREE.Sphere());const mesh=new THREE.Mesh(g,terrainMaterial);mesh.receiveShadow=true;scene.add(mesh);tile.mesh=mesh;tile.key=key}
function detailCorrection(x,z,a,b,baseY){const e=originE+x,n=originN-z,dem=mmlReady?fineHeight(e,n):NaN;if(!Number.isFinite(dem))return 0;
 if([a,b].some(id=>Number.isFinite(waterSurfaceIndex.sample(groundPositions[id*3],groundPositions[id*3+2])))||Number.isFinite(waterSurfaceIndex.sample(x,z)))return 0;
 const mod=(value)=>((value%4000)+4000)%4000,dx=mod(x),dz=mod(z),border=Math.min(dx,4000-dx,dz,4000-dz),fade=clamp(border/55,0,1);
 return (dem-baseY)*fade}
function refineTerrainTile(tile){if(tile.fineMesh)return;const pos=[],col=[],idx=[],vertexCache=new Map(),edgeCache=new Map(),baseColor=geo.attributes.color;
 function addBase(id){if(vertexCache.has(id))return vertexCache.get(id);const k=pos.length/3;for(let q=0;q<3;q++)pos.push(groundPositions[id*3+q]);for(let q=0;q<3;q++)col.push(baseColor.array[id*3+q]);vertexCache.set(id,k);return k}
 function midpoint(a,b){const key=Math.min(a,b)+','+Math.max(a,b);if(edgeCache.has(key))return edgeCache.get(key);const ia=a*3,ib=b*3,x=(groundPositions[ia]+groundPositions[ib])/2,z=(groundPositions[ia+2]+groundPositions[ib+2])/2,baseY=(groundPositions[ia+1]+groundPositions[ib+1])/2,y=baseY+detailCorrection(x,z,a,b,baseY),k=pos.length/3;pos.push(x,y,z);for(let q=0;q<3;q++)col.push((baseColor.array[a*3+q]+baseColor.array[b*3+q])/2);edgeCache.set(key,k);return k}
 for(let k=0;k<tile.indices.length;k+=3){const [a,b,c]=tile.indices.slice(k,k+3),ia=a*3,ib=b*3,ic=c*3,e=originE+(groundPositions[ia]+groundPositions[ib]+groundPositions[ic])/3,n=originN-(groundPositions[ia+2]+groundPositions[ib+2]+groundPositions[ic+2])/3,inRegion=e>=M.eMin&&e<=M.eMin+(M.cols-1)*M.step&&n<=M.nMax&&n>=M.nMax-(M.rows-1)*M.step,inCore=e>=G.eMin&&e<=G.eMin+width&&n<=G.nMax&&n>=G.nMax-depth,A=addBase(a),B=addBase(b),C=addBase(c);
  if(inRegion){const AB=midpoint(a,b),BC=midpoint(b,c),CA=midpoint(c,a);idx.push(A,AB,CA,AB,B,BC,CA,BC,C,AB,BC,CA)}else idx.push(A,B,C)}
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('color',new THREE.Float32BufferAttribute(col,3));g.setIndex(idx);g.computeVertexNormals();g.boundingSphere=tile.box.getBoundingSphere(new THREE.Sphere());const fine=new THREE.Mesh(g,terrainMaterial);fine.receiveShadow=true;scene.add(fine);tile.fineMesh=fine;tile.summerColors=new Float32Array(col);tile.mesh.visible=false;colorDetailTile(tile);localGroundSurfaces.set(tile.key,new SurfaceIndex(g.attributes.position.array,g.index.array))}
let lastTerrainDetail=null,detailRadius=dataSaver?0:1700,detailReload=null;function updateTerrainDetail(e,n,forceRoads=false){mml.requestAround(e,n,detailRadius);if(lastTerrainDetail&&Math.hypot(e-lastTerrainDetail[0],n-lastTerrainDetail[1])<500){if(forceRoads)scenery.updateLocalRoads(e,n,detailRadius,true);return}lastTerrainDetail=[e,n];const x=e-originE,z=originN-n;for(const tile of terrainTiles.values()){const closestX=clamp(x,tile.box.min.x,tile.box.max.x),closestZ=clamp(z,tile.box.min.z,tile.box.max.z),near=Math.hypot(x-closestX,z-closestZ)<detailRadius,region=tile.box.max.x>=M.eMin-originE&&tile.box.min.x<=M.eMin+(M.cols-1)*M.step-originE&&tile.box.max.z>=originN-M.nMax&&tile.box.min.z<=originN-(M.nMax-(M.rows-1)*M.step);if(near&&region)refineTerrainTile(tile);else if(tile.fineMesh){scene.remove(tile.fineMesh);tile.fineMesh.geometry.dispose();tile.fineMesh=null;tile.summerColors=null;tile.mesh.visible=true;localGroundSurfaces.delete(tile.key)}}scenery.updateLocalRoads(e,n,detailRadius,forceRoads)}

mml.onTileLoaded=()=>{if(detailReload)clearTimeout(detailReload);detailReload=setTimeout(()=>{for(const tile of terrainTiles.values())if(tile.fineMesh){scene.remove(tile.fineMesh);tile.fineMesh.geometry.dispose();tile.fineMesh=null;tile.summerColors=null;tile.mesh.visible=true;localGroundSurfaces.delete(tile.key)}lastTerrainDetail=null;updateTerrainDetail(observer.e,observer.n,true);scenery.updateLocalTrees(observer.e,observer.n,true)},600)};

const waterGeometry=new THREE.BufferGeometry();waterGeometry.setAttribute('position',new THREE.BufferAttribute(waterPositions,3));waterGeometry.setIndex(new THREE.BufferAttribute(waterIndices,1));waterGeometry.computeVertexNormals();
const waterMesh=new THREE.Mesh(waterGeometry,new THREE.MeshBasicMaterial({color:0x278dbc,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1}));waterMesh.name='Karttarajoihin sovitettu vesi';scene.add(waterMesh);
const lakeLife=window.createLakeLife(scene,window.LANDCOVER,originE,originN);
const infrastructure=window.createProjectInfrastructure(scene,height,originE,originN,G.turbines);
const scenery=window.addScenery(scene,height,originE,originN,M||G,infrastructure);scenery.setRenderQuality(renderLight,observer.e,observer.n);
const towerMat=new THREE.MeshStandardMaterial({color:0xdce4e7,metalness:.22,roughness:.68}),nacelleMat=new THREE.MeshStandardMaterial({color:0xe9edef,metalness:.15,roughness:.6}),bladeMat=new THREE.MeshStandardMaterial({color:0xe3e8eb,metalness:.07,roughness:.72,side:THREE.DoubleSide});const towerGeo=new THREE.CylinderGeometry(2.2,6.5,180,10),nacelleGeo=new THREE.BoxGeometry(15,8,20);const bladeShape=new THREE.Shape();bladeShape.moveTo(-3,0);bladeShape.lineTo(-6,25);bladeShape.lineTo(-5,65);bladeShape.lineTo(-1.1,99);bladeShape.lineTo(1,100);bladeShape.lineTo(3,65);bladeShape.lineTo(4,25);bladeShape.lineTo(3,0);bladeShape.closePath();const bladeGeo=new THREE.ExtrudeGeometry(bladeShape,{depth:1,bevelEnabled:false});const turbines=[];
for(const t of G.turbines){const p=local(t.e,t.n),h=height(t.e,t.n),group=new THREE.Group();group.position.set(p.x,h,p.z);group.rotation.y=Math.PI-windDegrees*Math.PI/180;const tower=new THREE.Mesh(towerGeo,towerMat);tower.position.y=90;tower.castShadow=true;group.add(tower);const nacelle=new THREE.Mesh(nacelleGeo,nacelleMat);nacelle.position.set(0,180,0);nacelle.castShadow=true;group.add(nacelle);const rotor=new THREE.Group();rotor.position.set(0,180,11);for(let b=0;b<3;b++){const blade=new THREE.Mesh(bladeGeo,bladeMat);blade.rotation.z=b*Math.PI*2/3;blade.castShadow=true;rotor.add(blade)}const hub=new THREE.Mesh(new THREE.SphereGeometry(3.3,12,8),nacelleMat);hub.castShadow=true;rotor.add(hub);group.add(rotor);scene.add(group);turbines.push({t,rotor,group})}
const windAudio=window.createWindAudio(G.turbines);
const soundBuildings=window.WIND_ACOUSTICS.createBuildingIndex(window.STRUCTURES?.buildings||[]);
function soundTerrain(e,n){const value=mml.sampleOverview(e,n);return Number.isFinite(value)?value:height(e,n)}
function soundCanopy(e,n){const canopy=window.CANOPY,i=Math.floor((e-canopy.eMin)/canopy.step),j=Math.floor((canopy.nMax-n)/canopy.step);if(i<0||i>=canopy.cols||j<0||j>=canopy.rows||window.LANDCOVER.inWater(e,n)||window.LANDCOVER.inField(e,n))return 0;return canopyMask[j*canopy.cols+i]||0}
let lastAcousticResult=null,lastAcousticAt=-Infinity;
function acousticResult(force=false){const now=performance.now();if(!force&&lastAcousticResult&&now-lastAcousticAt<180)return lastAcousticResult;lastAcousticAt=now;
 lastAcousticResult=window.WIND_ACOUSTICS.evaluate({observer:{e:observer.e,n:observer.n,height:viewerHeight},turbines:G.turbines,terrain:soundTerrain,canopy:soundCanopy,building:soundBuildings,water:window.LANDCOVER.inWater,cleared:projectPhase?infrastructure.cleared:null,windFrom:windDegrees,windSpeed:Number(el('windSpeed').value),temperature:Number(el('temperature').value),humidity:Number(el('humidity').value)/100,phase:projectPhase});return lastAcousticResult}
let projectPhase=1;function applyProjectPhase(){for(const t of turbines)t.group.visible=projectPhase===1;infrastructure.setPhase(projectPhase);scenery.setProjectPhase(projectPhase);document.querySelectorAll('[data-phase]').forEach(b=>{const active=Number(b.dataset.phase)===projectPhase;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});updateObserver()}
const obsMarker=new THREE.Group();const ring=new THREE.Mesh(new THREE.RingGeometry(14,21,36),new THREE.MeshBasicMaterial({color:0x64e2ed,side:THREE.DoubleSide,transparent:true,opacity:.95}));ring.rotation.x=-Math.PI/2;obsMarker.add(ring);const stem=new THREE.Mesh(new THREE.CylinderGeometry(1,1,32,8),new THREE.MeshBasicMaterial({color:0x64e2ed}));stem.position.y=16;obsMarker.add(stem);scene.add(obsMarker);
const routeStorageKey='niinimaki-camera-routes-v3';
const routeTarget=G.turbines.reduce((sum,t)=>({e:sum.e+t.e/G.turbines.length,n:sum.n+t.n/G.turbines.length}),{e:0,n:0});
const presetPose=(e,n,h,p=6)=>({e,n,height:h,yaw:Math.atan2(routeTarget.e-e,routeTarget.n-n),pitch:THREE.MathUtils.degToRad(p),fov:45});
const presetRoutes=[
 {name:'Renkajärven rannalta',points:[presetPose(343424,6759709,1.7),presetPose(343550,6759735,1.7),presetPose(343700,6759780,1.7)]},
 {name:'Renkajärven yllä',points:[presetPose(343424,6759709,20,3),presetPose(343650,6759800,45,3),presetPose(344000,6759950,65,3)]},
 {name:'Kohti voimaloita',points:[presetPose(344050,6760350,50,2),presetPose(344500,6760700,60,2),presetPose(345000,6761050,70,2)]}
];
const validRoutePoint=p=>p&&['e','n','height','yaw','pitch','fov'].every(key=>Number.isFinite(p[key]));
let routeSets=presetRoutes.map(route=>({name:route.name,points:route.points.map(p=>({...p}))})),activeRouteIndex=0,routePoints=routeSets[0].points,selectedRoutePoint=-1,routeMode=false;
try{const saved=JSON.parse(localStorage.getItem(routeStorageKey)||'null');if(saved&&Array.isArray(saved.routes)&&saved.routes.length){const cleaned=saved.routes.slice(0,24).map(route=>({name:String(route.name||'Oma reitti').slice(0,60),points:Array.isArray(route.points)?route.points.filter(validRoutePoint).slice(0,100):[]}));if(cleaned.length){routeSets=cleaned;activeRouteIndex=clamp(Number(saved.active)||0,0,routeSets.length-1);routePoints=routeSets[activeRouteIndex].points}}}catch{}
let routePlayback=null,routeLeafletLayer=null;
const map=el('map'),ctx=map.getContext('2d'),mapBase=document.createElement('canvas'),terrainRaster=document.createElement('canvas');let osmMap=null,osmActive=false,osmObserverMarker=null;let mapW=map.width,mapH=map.height,mapScale=1,lastCssWidth=0,mapScope='near',extent={eMin:originE,eMax:originE+width,nMax:originN,nMin:originN-depth};function mx(e){return (e-extent.eMin)/(extent.eMax-extent.eMin)*mapW}function my(n){return (extent.nMax-n)/(extent.nMax-extent.nMin)*mapH}function drawMap(){syncLeafletObserver();if(osmActive)return;const rasterScale=Math.min(1,1100/mapW,800/mapH),rasterW=Math.max(1,Math.round(mapW*rasterScale)),rasterH=Math.max(1,Math.round(mapH*rasterScale));terrainRaster.width=rasterW;terrainRaster.height=rasterH;const rasterCtx=terrainRaster.getContext('2d'),img=rasterCtx.createImageData(rasterW,rasterH);for(let y=0;y<rasterH;y++)for(let x=0;x<rasterW;x++){let e=extent.eMin+x/rasterW*(extent.eMax-extent.eMin),n=extent.nMax-y/rasterH*(extent.nMax-extent.nMin),k=(y*rasterW+x)*4;if(e<O.eMin||e>O.eMin+outerWidth||n>O.nMax||n<O.nMax-outerDepth){img.data[k]=27;img.data[k+1]=48;img.data[k+2]=56;img.data[k+3]=255;continue}let h=height(e,n),dx=height(e+70,n)-height(e-70,n),dy=height(e,n+70)-height(e,n-70),shade=clamp(15-dx*4+dy*5,-65,65),v=clamp((h-110)*.82,-22,78);img.data[k]=Math.floor(clamp(83+v+shade,0,255));img.data[k+1]=Math.floor(clamp(123+v*.72+shade,0,255));img.data[k+2]=Math.floor(clamp(96+v*.5+shade*.65,0,255));img.data[k+3]=255}rasterCtx.putImageData(img,0,0);ctx.clearRect(0,0,mapW,mapH);ctx.imageSmoothingEnabled=true;ctx.drawImage(terrainRaster,0,0,mapW,mapH);if(mapScope==='near'){ctx.fillStyle='#245a45b8';for(const forest of window.STRUCTURES?.forests||[]){const g=forest.geometry;if(g.length<3)continue;ctx.beginPath();g.forEach(([e,n],i)=>i?ctx.lineTo(mx(e),my(n)):ctx.moveTo(mx(e),my(n)));ctx.closePath();ctx.fill()}}for(const body of window.LANDCOVER?.bodies||[]){const outer=body.outer;if(outer.e1<extent.eMin||outer.e0>extent.eMax||outer.n1>extent.nMax||outer.n0<extent.nMin)continue;ctx.beginPath();for(const ring of [outer,...body.holes])ring.points.forEach(([e,n],i)=>i?ctx.lineTo(mx(e),my(n)):ctx.moveTo(mx(e),my(n)));ctx.fillStyle='#178ed2';ctx.fill('evenodd')}if(mapScope==='wide'){ctx.beginPath();ctx.arc(mx(346500),my(6761500),mapW/2,0,Math.PI*2);ctx.strokeStyle='#ffffffaa';ctx.lineWidth=2;ctx.stroke()}
let fieldNo=0;for(const feature of (mapScope==='wide'?window.WIDE_MAP_FEATURES:window.MAP_FEATURES)||[]){const g=feature.geometry;if(!g||g.length<2)continue;ctx.beginPath();let valid=0;for(const [e,n] of g){const x=mx(e),y=my(n);if(valid++===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}if(feature.kind==='water'){ctx.closePath();ctx.fillStyle='#178ed2';ctx.fill()}else if(feature.kind==='field'){ctx.closePath();ctx.fillStyle=['#c7ae6b','#d8bd7c','#bba86d','#d2ba86','#c9b779','#c0b370','#d4b772','#c8ba70'][(window.LANDCOVER.fields[fieldNo++]?.shade)||0];ctx.fill()}else{const roadClass=window.ROAD_STYLES?.[feature.id]??(feature.kind==='main'?1:0);ctx.strokeStyle=['#bed1c6','#454c4d','#81796c','#806446','#bed1c6'][roadClass];ctx.lineWidth=[1.1,3,1.1,.65,.8][roadClass];ctx.stroke()}}
if(mapScope==='near'){ctx.strokeStyle='#168fd1';ctx.lineCap='round';for(const stream of window.WATERWAYS||[]){const pts=stream.geometry;if(pts.length<2)continue;ctx.beginPath();pts.forEach(([e,n],i)=>i?ctx.lineTo(mx(e),my(n)):ctx.moveTo(mx(e),my(n)));ctx.lineWidth=Math.max(1,stream.width*2/(extent.eMax-extent.eMin)*mapW);ctx.stroke()}}ctx.strokeStyle='#ffffff77';ctx.lineWidth=1;for(let x=0;x<mapW;x+=mapW/5){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,mapH);ctx.stroke()}for(let y=0;y<mapH;y+=mapH/4){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(mapW,y);ctx.stroke()}
for(const t of G.turbines){const x=mx(t.e),y=my(t.n);ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fillStyle='#f3f5ef';ctx.fill();ctx.strokeStyle='#163846';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#12323a';ctx.font='bold 9px system-ui';ctx.textAlign='center';ctx.fillText(String(t.id),x,y+3)}ctx.fillStyle='#d8eaec';ctx.font='bold 11px system-ui';ctx.textAlign='left';ctx.fillText('P',8,16);if(mapScope==='near'){ctx.font='bold 9px system-ui';ctx.textAlign='center';ctx.lineWidth=3;ctx.strokeStyle='#15343c';ctx.strokeText('Renkajärventie',mx(346552),my(6758687)-7);ctx.fillStyle='#edf8f7';ctx.fillText('Renkajärventie',mx(346552),my(6758687)-7)}if(mapScope==='wide'){ctx.fillStyle='#e8f2f2';ctx.font='bold 11px system-ui';ctx.textAlign='left';ctx.fillText('45 km tarkastelu',9,mapH-12)}drawRouteCanvas();mapBase.width=map.width;mapBase.height=map.height;mapBase.getContext('2d').drawImage(map,0,0);drawObserverMarker()}function drawObserverMarker(){syncLeafletObserver();if(osmActive)return;if(mapBase.width!==map.width)return;ctx.setTransform(1,0,0,1,0,0);ctx.drawImage(mapBase,0,0);ctx.setTransform(mapScale,0,0,mapScale,0,0);const x=mx(observer.e),y=my(observer.n);ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fillStyle='#61dded';ctx.fill();ctx.strokeStyle='#10343d';ctx.lineWidth=2;ctx.stroke();ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.fillStyle='#10343d';ctx.fill();if(mode==='ground'){const dx=Math.sin(yaw),dy=-Math.cos(yaw),sideX=-dy,sideY=dx;ctx.beginPath();ctx.moveTo(x+dx*11,y+dy*11);ctx.lineTo(x+dx*31,y+dy*31);ctx.strokeStyle='#083b47';ctx.lineWidth=6;ctx.lineCap='round';ctx.stroke();ctx.beginPath();ctx.moveTo(x+dx*34,y+dy*34);ctx.lineTo(x+dx*21+sideX*7,y+dy*21+sideY*7);ctx.lineTo(x+dx*21-sideX*7,y+dy*21-sideY*7);ctx.closePath();ctx.fillStyle='#ffb13b';ctx.fill();ctx.strokeStyle='#083b47';ctx.lineWidth=2;ctx.stroke()}}
function drawRouteCanvas(){
 if(!routeMode||!routePoints.length)return;
 ctx.save();ctx.strokeStyle='#f6a928';ctx.fillStyle='#fff9df';ctx.lineWidth=2.5;ctx.beginPath();routePoints.forEach((point,i)=>i?ctx.lineTo(mx(point.e),my(point.n)):ctx.moveTo(mx(point.e),my(point.n)));ctx.stroke();
 routePoints.forEach((point,i)=>{const x=mx(point.e),y=my(point.n);ctx.beginPath();ctx.arc(x,y,i===selectedRoutePoint?11:8,0,Math.PI*2);ctx.fillStyle=i===selectedRoutePoint?'#f6a928':'#fff9df';ctx.fill();ctx.strokeStyle='#174b50';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#174b50';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.fillText(String(i+1),x,y+3)});ctx.restore()
}
function drawRouteLeaflet(){
 if(!osmMap||!window.L)return;if(routeLeafletLayer)routeLeafletLayer.remove();routeLeafletLayer=null;if(!routeMode)return;routeLeafletLayer=L.layerGroup().addTo(osmMap);
 const points=routePoints.map(point=>{const [lon,lat]=proj4(FIN,'EPSG:4326',[point.e,point.n]);return[lat,lon]});
 if(points.length>1)L.polyline(points,{color:'#ec9c27',weight:3,opacity:.9,interactive:false}).addTo(routeLeafletLayer);
 points.forEach((point,i)=>L.marker(point,{interactive:true,icon:L.divIcon({className:'route-leaflet'+(i===selectedRoutePoint?' selected':''),html:String(i+1),iconSize:[24,24],iconAnchor:[12,12]})}).on('click',event=>{L.DomEvent.stopPropagation(event);selectRoutePoint(i)}).addTo(routeLeafletLayer))
}
function formatDistance(m){return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(2).replace('.',',')} km`}
function updateAcousticMetrics(force=false){const result=acousticResult(force),nearest=Math.min(...G.turbines.map(t=>Math.hypot(t.e-observer.e,t.n-observer.n)));
 el('distanceText').textContent=formatDistance(nearest);
 el('soundText').textContent=projectPhase===0?'Ei voimaloita':nearest<300?'Lähialue: ei arviota*':result.level<15?'hyvin vaimea*':`≈ ${result.level.toFixed(0)} dB(A)*`;
 el('soundText').title='Suuntaa antava etenemisarvio 107,8 dB(A) ilmoitetulla ääniteholla. Hankkeen selvityksen +2 dB lähtöarvolisä ei ole tämän arvion kokonaisepävarmuus.';
 el('info').textContent=`${window.LANDCOVER.bodyAt(observer.e,observer.n)?'Veneessä · ':window.LANDCOVER.inWater(observer.e,observer.n)?'Puron kohdalla · ':''}Lähin voimala ${formatDistance(nearest)} päässä`}
function updateObserver(){const p=local(observer.e,observer.n);obsMarker.position.set(p.x,height(observer.e,observer.n)+3,p.z);updateAcousticMetrics();el('coords').textContent=`E ${Math.round(observer.e)} · N ${Math.round(observer.n)}`;drawMap();updateSun()}
const FIN='+proj=utm +zone=35 +ellps=GRS80 +units=m +no_defs';function finnishOffset(y,m,d,hour){const lastSunday=(year,month)=>{const a=new Date(Date.UTC(year,month+1,0));return a.getUTCDate()-a.getUTCDay()};const start=lastSunday(y,2),end=lastSunday(y,9);return (m>3&&m<10)||(m===3&&(d>start||(d===start&&hour>=3)))||(m===10&&(d<end||(d===end&&hour<4)))?3:2}
function selectedDate(){const v=el('date').value||'2026-06-21';let [Y,M,D]=v.split('-').map(Number);M=clamp(M,1,12);D=clamp(D,1,31);const hour=Math.floor(timeMinutes/60),offset=finnishOffset(Y,M,D,hour);return new Date(Date.UTC(Y,M-1,D,hour-offset,timeMinutes%60))}
function updateSun(){const [lon,lat]=proj4(FIN,'EPSG:4326',[observer.e,observer.n]),a=SunCalc.getPosition(selectedDate(),lat,lon);const alt=a.altitude,az=a.azimuth;const sx=-Math.sin(az),sz=Math.cos(az),sy=Math.tan(Math.max(.035,alt));const norm=Math.hypot(sx,sy,sz);sun.position.set(5000+sx/norm*6500,300+sy/norm*6500,4000+sz/norm*6500);sun.target.position.set(5000,130,4000);sun.target.updateMatrixWorld();sun.visible=alt>0;hemi.intensity=alt<-.1?.12:alt<.09?.2:.28;sun.intensity=alt>0?clamp(.72+Math.sin(alt)*1.05,.72,1.65):0;scene.background.set(alt<-.1?0x203946:alt<.09?0x657f91:0x91bdcd);scene.fog.color.copy(scene.background);el('sunText').textContent=alt>0?`${Math.round(THREE.MathUtils.radToDeg(alt))}° korkeudella`:'horisontin alla';el('timeText').textContent=`${String(Math.floor(timeMinutes/60)).padStart(2,'0')}.${String(timeMinutes%60).padStart(2,'0')}`;el('time').value=String(timeMinutes);updateSeason()}
function setFieldOfView(){camera.fov=mode==='ground'?THREE.MathUtils.radToDeg(2*Math.atan(Math.tan(THREE.MathUtils.degToRad(Number(el('fov').value))/2)/camera.aspect)):54;camera.updateProjectionMatrix()}function lookDirection(){return new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch))}
function setGround(){mode='ground';updateTerrainDetail(observer.e,observer.n);scenery.setGroundMode(true,observer.e,observer.n);controls.enabled=false;setFieldOfView();let near=G.turbines.reduce((a,b)=>Math.hypot(a.e-observer.e,a.n-observer.n)<Math.hypot(b.e-observer.e,b.n-observer.n)?a:b);yaw=Math.atan2(near.e-observer.e,near.n-observer.n);pitch=.08;const p=local(observer.e,observer.n);camera.position.set(p.x,walkingHeight(observer.e,observer.n),p.z);obsMarker.visible=false;syncCameraControls();drawObserverMarker();camera.lookAt(camera.position.clone().add(lookDirection()));el('status').hidden=true}
function setObserver(e,n){if(routePlayback)stopRoute();viewerHeight=1.7;observer.e=clamp(e,O.eMin+5,O.eMin+outerWidth-5);observer.n=clamp(n,O.nMax-outerDepth+5,O.nMax-5);updateObserver();if(osmActive)osmMap.panTo(observerLatLng(),{animate:false});if(mode==='ground')setGround()}
const projectCenter=G.turbines.reduce((sum,t)=>({e:sum.e+t.e/G.turbines.length,n:sum.n+t.n/G.turbines.length}),{e:0,n:0});
function faceProjectCenter(){yaw=Math.atan2(projectCenter.e-observer.e,projectCenter.n-observer.n);pitch=THREE.MathUtils.degToRad(6);updateCameraView()}
const settingsPanel=el('settingsPanel');new ResizeObserver(()=>document.documentElement.style.setProperty('--panel-bottom',settingsPanel.getBoundingClientRect().bottom+'px')).observe(settingsPanel);
el('timelineToggle').onclick=()=>{const closed=settingsPanel.classList.toggle('closed');el('timelineToggle').textContent=closed?'▼':'▲';el('timelineToggle').setAttribute('aria-expanded',String(!closed));el('timelineToggle').setAttribute('aria-label',closed?'Näytä aikasäätimet':'Piilota aikasäätimet')};
el('dockToggle').onclick=()=>{const closed=el('controlDock').classList.toggle('closed');el('dockToggle').setAttribute('aria-expanded',String(!closed));el('dockToggle').setAttribute('aria-label',closed?'Näytä ohjaus':'Piilota ohjaus')};
if(window.innerWidth<=700){settingsPanel.classList.add('closed');el('timelineToggle').textContent='▼';el('timelineToggle').setAttribute('aria-expanded','false');el('timelineToggle').setAttribute('aria-label','Näytä aikasäätimet');}
el('helpToggle').onclick=()=>el('helpPopover').hidden=!el('helpPopover').hidden;
el('helpClose').onclick=()=>el('helpPopover').hidden=true;
const drawer=el('mapDrawer');let drawerWidth=window.innerWidth<=700?42:370;function centerMapOnObserver(w=extent.eMax-extent.eMin,h=extent.nMax-extent.nMin){extent={eMin:observer.e-w/2,eMax:observer.e+w/2,nMin:observer.n-h/2,nMax:observer.n+h/2}}function resizeMapCanvas(){if(osmActive){osmMap.invalidateSize({pan:false});osmMap.panTo(observerLatLng(),{animate:false});return}const rect=map.getBoundingClientRect();if(rect.width<1||rect.height<1)return;const metersPerCssPixel=(extent.eMax-extent.eMin)/(lastCssWidth||rect.width);lastCssWidth=rect.width;mapW=Math.max(80,Math.round(rect.width));mapH=Math.max(60,Math.round(rect.height));mapScale=Math.min(window.devicePixelRatio||1,2);map.width=Math.round(mapW*mapScale);map.height=Math.round(mapH*mapScale);ctx.setTransform(mapScale,0,0,mapScale,0,0);centerMapOnObserver(metersPerCssPixel*rect.width,metersPerCssPixel*rect.height);drawMap()}let resizeQueued=false;function queueMapResize(){if(resizeQueued)return;resizeQueued=true;requestAnimationFrame(()=>{resizeQueued=false;resizeMapCanvas()})}function setDrawerWidth(w){drawerWidth=clamp(w,42,window.innerWidth);drawer.classList.toggle('collapsed',window.innerWidth>700&&drawerWidth<120);document.documentElement.style.setProperty('--drawer-width',`${drawerWidth}px`);drawer.classList.toggle('compact',window.innerWidth>700&&drawerWidth<290);queueMapResize()}setDrawerWidth(drawerWidth);new ResizeObserver(queueMapResize).observe(el('map').parentElement);
const mobileMapToggle=el('mobileMapToggle');let mapPullStart=null;
function setMobileMapOpen(open){drawer.classList.toggle('mobile-open',open);mobileMapToggle.textContent=open?'Kartta ▼':'Kartta ▲';mobileMapToggle.setAttribute('aria-expanded',String(open));mobileMapToggle.setAttribute('aria-label',open?'Sulje kartta alareunaan':'Avaa kartta alareunasta');if(open)queueMapResize()}
mobileMapToggle.addEventListener('pointerdown',e=>{mapPullStart=e.clientY;mobileMapToggle.setPointerCapture(e.pointerId)});
mobileMapToggle.addEventListener('pointerup',e=>{const dy=e.clientY-(mapPullStart??e.clientY);setMobileMapOpen(Math.abs(dy)>25?dy<0:!drawer.classList.contains('mobile-open'));mapPullStart=null;e.preventDefault()});
mobileMapToggle.addEventListener('pointercancel',()=>{mapPullStart=null});
mobileMapToggle.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setMobileMapOpen(!drawer.classList.contains('mobile-open'))}});
let panelPullStart=null;el('settingsPanel').querySelector('.yearHead').addEventListener('pointerdown',e=>{if(window.innerWidth<=700&&!e.target.closest('button,input'))panelPullStart=e.clientY});el('settingsPanel').querySelector('.yearHead').addEventListener('pointerup',e=>{if(panelPullStart===null)return;const dy=e.clientY-panelPullStart;panelPullStart=null;if(Math.abs(dy)<25)return;const closed=dy<0;settingsPanel.classList.toggle('closed',closed);el('timelineToggle').textContent=closed?'▼':'▲';el('timelineToggle').setAttribute('aria-expanded',String(!closed))});
let edgeDragging=false;el('drawerEdge').addEventListener('pointerdown',e=>{edgeDragging=true;drawer.classList.add('resizing');el('drawerEdge').setPointerCapture(e.pointerId);e.preventDefault()});el('drawerEdge').addEventListener('pointermove',e=>{if(edgeDragging)setDrawerWidth(e.clientX)});for(const eventName of ['pointerup','pointercancel'])el('drawerEdge').addEventListener(eventName,()=>{edgeDragging=false;drawer.classList.remove('resizing')});el('drawerEdge').addEventListener('dblclick',()=>setDrawerWidth(drawerWidth<120?Math.min(420,window.innerWidth*.8):42));el('drawerEdge').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){setDrawerWidth(drawerWidth+(e.key==='ArrowRight'?40:-40));e.preventDefault()}});
function mapPoint(clientX,clientY){const r=map.getBoundingClientRect();return{x:(clientX-r.left)/r.width,y:(clientY-r.top)/r.height}}function zoomMap(factor,px=.5,py=.5){if(osmActive){osmMap.setZoom(osmMap.getZoom()+(factor<1?1:-1));return}const w=extent.eMax-extent.eMin,h=extent.nMax-extent.nMin,nw=clamp(w*factor,300,120000),nh=h*nw/w,anchorE=extent.eMin+px*w,anchorN=extent.nMax-py*h;extent={eMin:anchorE-px*nw,eMax:anchorE+(1-px)*nw,nMax:anchorN+py*nh,nMin:anchorN-(1-py)*nh};drawMap()}el('zoomIn').onclick=()=>zoomMap(.68);el('zoomOut').onclick=()=>zoomMap(1/.68);map.addEventListener('wheel',e=>{e.preventDefault();const q=mapPoint(e.clientX,e.clientY);zoomMap(Math.exp(clamp(e.deltaY,-400,400)*.0012),q.x,q.y)},{passive:false});
const mapPointers=new Map();let mapMoved=false,lastPinch=0;map.addEventListener('pointerdown',e=>{map.setPointerCapture(e.pointerId);mapPointers.set(e.pointerId,{x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY});mapMoved=false;lastPinch=0;e.preventDefault()});map.addEventListener('pointermove',e=>{if(!mapPointers.has(e.pointerId))return;const old=mapPointers.get(e.pointerId);if(Math.hypot(e.clientX-old.sx,e.clientY-old.sy)>5)mapMoved=true;mapPointers.set(e.pointerId,{...old,x:e.clientX,y:e.clientY});if(mapPointers.size>=2){const a=[...mapPointers.values()],distance=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(lastPinch){const q=mapPoint((a[0].x+a[1].x)/2,(a[0].y+a[1].y)/2);zoomMap(lastPinch/distance,q.x,q.y)}lastPinch=distance;mapMoved=true;return}if(mapMoved){const r=map.getBoundingClientRect(),de=(e.clientX-old.x)/r.width*(extent.eMax-extent.eMin),dn=(e.clientY-old.y)/r.height*(extent.nMax-extent.nMin);extent.eMin-=de;extent.eMax-=de;extent.nMin+=dn;extent.nMax+=dn;drawMap()}});map.addEventListener('pointerup',e=>mapPointers.delete(e.pointerId));map.addEventListener('pointercancel',e=>mapPointers.delete(e.pointerId));map.addEventListener('dblclick',e=>{e.preventDefault();const q=mapPoint(e.clientX,e.clientY);setObserver(extent.eMin+q.x*(extent.eMax-extent.eMin),extent.nMax-q.y*(extent.nMax-extent.nMin));centerMapOnObserver();drawMap()});map.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setGround()}});
el('scopeBtn').onclick=()=>{mapScope=mapScope==='near'?'wide':'near';if(osmActive){if(mapScope==='near')osmMap.setView(observerLatLng(),13,{animate:false});else{const ll=(e,n)=>{const p=proj4(FIN,'EPSG:4326',[e,n]);return[p[1],p[0]]};osmMap.fitBounds([ll(335000,6749000),ll(359000,6775000)],{animate:false})}}const rect=map.getBoundingClientRect(),w=mapScope==='wide'?26000:width;centerMapOnObserver(w,w*rect.height/Math.max(1,rect.width));el('mapTitle').textContent=mapScope==='wide'?'Koko mallinnettu alue':'Lähialue';el('scopeBtn').textContent=mapScope==='wide'?'Lähialue':'Koko alue';drawMap()};
function routePointAtMap(clientX,clientY){if(!routeMode||osmActive)return-1;const q=mapPoint(clientX,clientY),x=q.x*mapW,y=q.y*mapH;return routePoints.findIndex(p=>Math.hypot(mx(p.e)-x,my(p.n)-y)<14/mapScale)}
map.addEventListener('click',event=>{if(mapMoved)return;const index=routePointAtMap(event.clientX,event.clientY);if(index>=0){event.preventDefault();selectRoutePoint(index)}});
map.addEventListener('dblclick',event=>{const index=routePointAtMap(event.clientX,event.clientY);if(index>=0){event.preventDefault();event.stopImmediatePropagation();selectRoutePoint(index)}},true);
function observerLatLng(){const [lon,lat]=proj4(FIN,'EPSG:4326',[observer.e,observer.n]);return[lat,lon]}function syncLeafletObserver(){if(!osmObserverMarker)return;osmObserverMarker.setLatLng(observerLatLng());const icon=osmObserverMarker.getElement(),arrow=icon?.querySelector('.obsArrow');if(arrow){arrow.style.transform=`rotate(${THREE.MathUtils.radToDeg(yaw)}deg)`;arrow.style.visibility=mode==='ground'?'visible':'hidden'}}function initLeaflet(){if(dataSaver)return;if(location.protocol==='file:'){el('mapSourceNotice').textContent='Tavallinen OSM-kartta näkyy, kun avaat demon työpöytäkansion käynnistystiedostosta.';el('mapSourceNotice').hidden=false;return}if(!window.L)return;try{osmMap=L.map('osmMap',{zoomControl:false,doubleClickZoom:false,attributionControl:true,zoomSnap:.5,zoomDelta:.5,minZoom:8,maxZoom:18,preferCanvas:true}).setView(observerLatLng(),13);const tile=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a>',maxZoom:19,keepBuffer:1,updateWhenIdle:true});let failed=0;tile.on('tileload',()=>{if(dataSaver)return;if(!osmActive){osmActive=true;el('osmMap').parentElement.classList.add('osm-active');resizeMapCanvas();syncLeafletObserver()}});tile.on('tileerror',()=>{if(++failed>=3&&!osmActive){el('osmMap').parentElement.classList.add('osm-failed');el('mapSourceNotice').textContent='OSM-kartta ei latautunut. Näytetään paikallinen kartta.';el('mapSourceNotice').hidden=false;osmMap.remove();osmMap=null}});tile.addTo(osmMap);drawRouteLeaflet();for(const t of G.turbines){const [lon,lat]=proj4(FIN,'EPSG:4326',[t.e,t.n]);L.marker([lat,lon],{icon:L.divIcon({className:'turbine-leaflet',html:String(t.id),iconSize:[23,23],iconAnchor:[11.5,11.5]}),interactive:false}).addTo(osmMap)}osmObserverMarker=L.marker(observerLatLng(),{icon:L.divIcon({className:'observer-leaflet',html:'<div class="obsArrow"></div><div class="obsDot"></div>',iconSize:[40,40],iconAnchor:[20,20]}),interactive:false}).addTo(osmMap);syncLeafletObserver();osmMap.on('dblclick',event=>{const [e,n]=proj4('EPSG:4326',FIN,[event.latlng.lng,event.latlng.lat]);setObserver(e,n)})}catch(error){console.warn('OpenStreetMap-kartta ei latautunut, käytetään paikallista karttaa.',error);osmMap=null;el('osmMap').parentElement.classList.add('osm-failed')}}
let leafletLoading=null;function startLeaflet(){if(dataSaver||location.protocol==='file:')return;if(window.L){initLeaflet();return}if(!leafletLoading)leafletLoading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='assets/leaflet.js';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)});leafletLoading.then(()=>{if(!dataSaver&&!osmMap)initLeaflet()}).catch(error=>console.warn('Karttapalvelu ei latautunut',error))}function stopLeaflet(){if(osmMap)osmMap.remove();osmMap=null;osmActive=false;osmObserverMarker=null;routeLeafletLayer=null;el('osmMap').parentElement.classList.remove('osm-active');el('mapSourceNotice').hidden=true;resizeMapCanvas()}
const windNames=['pohjoisesta','koillisesta','idästä','kaakosta','etelästä','lounaasta','lännestä','luoteesta'];function updateWind(){windDegrees=Number(el('wind').value)%360;const label=windNames[Math.round(windDegrees/45)%8];el('windText').textContent=`${label} (${windDegrees}°)`;for(const t of turbines)t.group.rotation.y=Math.PI-windDegrees*Math.PI/180;updateAcousticMetrics(true)}el('wind').addEventListener('input',updateWind);updateWind();el('date').addEventListener('change',()=>{syncYearDial();updateSun()});
const yearDial=el('yearDial');const monthNames=['Tam','Hel','Maa','Huh','Tou','Kes','Hei','Elo','Syy','Lok','Mar','Jou'];monthNames.forEach((name,i)=>{const mark=document.createElement('span'),angle=(45+i*30)*Math.PI/180;mark.className='yearDialMonth';mark.textContent=name;mark.style.left=(50+45*Math.sin(angle))+'%';mark.style.top=(50-45*Math.cos(angle))+'%';yearDial.appendChild(mark)});let dialDragging=false,dialPrevious=null;
function dialDay(event){const box=yearDial.getBoundingClientRect(),angle=Math.atan2(event.clientY-(box.top+box.height/2),event.clientX-(box.left+box.width/2)),fraction=((angle+Math.PI/3+Math.PI*2)%(Math.PI*2))/(Math.PI*2),year=Number(el('date').value.slice(0,4))||2026,days=new Date(year,1,29).getMonth()===1?366:365;return Math.min(days-1,Math.floor(fraction*days))}
function selectDialDay(day,wrap=false){const year=Number(el('date').value.slice(0,4))||2026,date=new Date(Date.UTC(year,0,day+1));if(wrap)date.setUTCFullYear(date.getUTCFullYear()+wrap);el('date').value=date.toISOString().slice(0,10);syncYearDial();updateSun()}
yearDial.addEventListener('pointerdown',event=>{dialDragging=true;yearDial.setPointerCapture(event.pointerId);const day=dialDay(event);dialPrevious=day;selectDialDay(day);event.preventDefault()});
yearDial.addEventListener('pointermove',event=>{if(!dialDragging)return;const day=dialDay(event),year=Number(el('date').value.slice(0,4))||2026,days=new Date(year,1,29).getMonth()===1?366:365,wrap=dialPrevious>days*.75&&day<days*.25?1:dialPrevious<days*.25&&day>days*.75?-1:0;dialPrevious=day;selectDialDay(day,wrap)});
for(const name of ['pointerup','pointercancel'])yearDial.addEventListener(name,()=>{dialDragging=false;dialPrevious=null});
yearDial.addEventListener('keydown',event=>{const delta=event.key==='ArrowRight'||event.key==='ArrowUp'?1:event.key==='ArrowLeft'||event.key==='ArrowDown'?-1:event.key==='PageUp'?30:event.key==='PageDown'?-30:0;if(!delta)return;const date=new Date(el('date').value+'T12:00:00');date.setDate(date.getDate()+delta);el('date').value=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');syncYearDial();updateSun();event.preventDefault()});el('time').addEventListener('input',e=>{timeMinutes=Number(e.target.value);updateSun()});el('playBtn').onclick=()=>{playing=!playing;el('playBtn').textContent=playing?'Ⅱ Pysäytä aika':'▶ Ajan kulku'};
el('timeRate').addEventListener('input',()=>el('timeRateText').textContent=['1×','2×','4×','10×','20×'][Number(el('timeRate').value)]);
el('windSpeed').addEventListener('input',()=>{el('windSpeedText').textContent=el('windSpeed').value+' m/s';updateAcousticMetrics(true)});
for(const [id,out,suffix] of [['temperature','temperatureText',' °C'],['humidity','humidityText',' %']])el(id).addEventListener('input',()=>{el(out).textContent=el(id).value+suffix;updateAcousticMetrics(true)});
function applyTerrainChoice(){const level=Number(el('terrainQuality').value);detailRadius=dataSaver?0:[0,1700,3200][level];el('terrainQualityText').textContent=dataSaver?'Tiedonsäästö':['Kevyt','Normaali','Tarkka'][level];lastTerrainDetail=null;updateTerrainDetail(observer.e,observer.n,true);scenery.updateLocalTrees(observer.e,observer.n,true)}el('terrainQuality').addEventListener('input',applyTerrainChoice);
el('lightRender').checked=renderLight;el('dataSaver').checked=dataSaver;if(dataSaver)el('terrainQualityText').textContent='Tiedonsäästö';el('lightRender').addEventListener('change',()=>{renderLight=el('lightRender').checked;savePreference('niinimaki-light-render',renderLight);renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,renderLight?1:1.5));sun.shadow.mapSize.set(renderLight?1024:3072,renderLight?1024:3072);if(sun.shadow.map){sun.shadow.map.dispose();sun.shadow.map=null}renderer.shadowMap.needsUpdate=true;scenery.setRenderQuality(renderLight,observer.e,observer.n);resize()});el('dataSaver').addEventListener('change',()=>{dataSaver=el('dataSaver').checked;savePreference('niinimaki-data-saver',dataSaver);if(dataSaver)stopLeaflet();else startLeaflet();applyTerrainChoice()});
document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{projectPhase=Number(b.dataset.phase);applyProjectPhase()});
function syncCameraControls(){el('angle').value=String((Math.round(THREE.MathUtils.radToDeg(yaw))%360+360)%360);el('angleText').textContent=`${el('angle').value}°`;el('tilt').value=String(Math.round(THREE.MathUtils.radToDeg(pitch)));el('tiltText').textContent=`${el('tilt').value}°`;el('height').value=String(viewerHeight);el('heightText').textContent=`${viewerHeight.toFixed(1).replace('.',',')} m`;el('compassRose').style.setProperty('--compass-angle',`${-THREE.MathUtils.radToDeg(yaw)}deg`)}function updateCameraView(){if(mode==='ground'){camera.lookAt(camera.position.clone().add(lookDirection()));drawObserverMarker()}syncCameraControls()}el('angle').addEventListener('input',e=>{yaw=THREE.MathUtils.degToRad(Number(e.target.value));updateCameraView()});el('tilt').addEventListener('input',e=>{pitch=THREE.MathUtils.degToRad(Number(e.target.value));updateCameraView()});el('height').addEventListener('input',e=>{viewerHeight=clamp(Number(e.target.value),1.7,500);if(mode==='ground')camera.position.y=walkingHeight(originE+camera.position.x,originN-camera.position.z);updateCameraView();updateAcousticMetrics(true)});el('fov').addEventListener('input',e=>{el('fovText').textContent=`${e.target.value}°`;setFieldOfView()});el('fov').parentElement.addEventListener('dblclick',event=>{el('fov').value='45';el('fovText').textContent='45°';setFieldOfView();event.preventDefault()});renderer.domElement.addEventListener('wheel',e=>{if(mode!=='ground')return;e.preventDefault();if(e.shiftKey){viewerHeight=clamp(viewerHeight-e.deltaY*.06,1.7,500);camera.position.y=walkingHeight(originE+camera.position.x,originN-camera.position.z);updateCameraView()}else{const fov=clamp(Number(el('fov').value)*Math.exp(e.deltaY*.0012),5,90);el('fov').value=String(fov);el('fovText').textContent=`${Math.round(fov)}°`;setFieldOfView()}},{passive:false});
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),sceneTouches=new Map();let pinchStartDistance=0,pinchStartFov=45;
renderer.domElement.addEventListener('pointerdown',e=>{downX=lastX=e.clientX;downY=lastY=e.clientY;downTime=performance.now();if(mode!=='ground')return;renderer.domElement.setPointerCapture(e.pointerId);if(e.pointerType==='touch'){sceneTouches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(sceneTouches.size===2){const [a,b]=[...sceneTouches.values()];pinchStartDistance=Math.hypot(a.x-b.x,a.y-b.y);pinchStartFov=Number(el('fov').value);dragging=false;return}}dragging=true});
renderer.domElement.addEventListener('pointermove',e=>{if(mode!=='ground')return;if(e.pointerType==='touch'&&sceneTouches.has(e.pointerId)){sceneTouches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(sceneTouches.size>=2){const [a,b]=[...sceneTouches.values()],distance=Math.hypot(a.x-b.x,a.y-b.y);if(distance>8&&pinchStartDistance>8){const fov=clamp(pinchStartFov*pinchStartDistance/distance,5,90);el('fov').value=String(fov);el('fovText').textContent=`${Math.round(fov)}°`;setFieldOfView()}return}}if(dragging){yaw-=(e.clientX-lastX)*.004;pitch=clamp(pitch+(e.clientY-lastY)*.0035,-1.25,1.25);updateCameraView();lastX=e.clientX;lastY=e.clientY}});
for(const name of ['pointerup','pointercancel'])renderer.domElement.addEventListener(name,e=>{sceneTouches.delete(e.pointerId);dragging=false;if(sceneTouches.size<2)pinchStartDistance=0});
renderer.domElement.addEventListener('dblclick',e=>{
 e.preventDefault();
 const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);
 const hit=ray.intersectObjects([terrain,waterMesh])[0];if(!hit)return;
 const easting=originE+hit.point.x,northing=originN-hit.point.z;
 if(mode==='ground'){
  observer.e=clamp(easting,O.eMin+5,O.eMin+outerWidth-5);observer.n=clamp(northing,O.nMax-outerDepth+5,O.nMax-5);
  updateObserver();updateTerrainDetail(observer.e,observer.n);if(osmActive)osmMap.panTo(observerLatLng(),{animate:false});
  const p=local(observer.e,observer.n);camera.position.set(p.x,walkingHeight(observer.e,observer.n),p.z);updateCameraView();
 }else{setObserver(easting,northing);setGround()}
});
let lastMapRefresh=0;const keyset=new Set(),walkSpeeds=[3,20,120];let walkSpeedIndex=0,joyX=0,joyY=0;
const joystick=el('mobileJoystick'),joystickKnob=el('joystickKnob');function resetJoystick(){joyX=joyY=0;joystickKnob.style.transform='translate(0px,0px)'}function moveJoystick(e){const box=joystick.getBoundingClientRect(),radius=box.width*.34,dx=e.clientX-box.left-box.width/2,dy=e.clientY-box.top-box.height/2,length=Math.hypot(dx,dy),scale=length>radius?radius/length:1;joyX=clamp(dx/radius,-1,1);joyY=clamp(dy/radius,-1,1);joystickKnob.style.transform=`translate(${dx*scale}px,${dy*scale}px)`}
joystick.addEventListener('pointerdown',e=>{joystick.setPointerCapture(e.pointerId);moveJoystick(e);e.preventDefault()});joystick.addEventListener('pointermove',e=>{if(joystick.hasPointerCapture(e.pointerId))moveJoystick(e)});for(const name of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(name,resetJoystick);
function updateWalkSpeed(){document.querySelectorAll('[data-speed]').forEach((b,i)=>b.classList.toggle('active',i===walkSpeedIndex))}updateWalkSpeed();document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{walkSpeedIndex=Number(b.dataset.speed);updateWalkSpeed()});window.addEventListener('keydown',e=>{if(e.code==='KeyQ'&&mode==='ground'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){if(!e.repeat){walkSpeedIndex=(walkSpeedIndex+1)%3;updateWalkSpeed()}e.preventDefault();return}if(/^(ArrowUp|ArrowDown|ArrowLeft|ArrowRight|KeyW|KeyS|KeyD|KeyE|ShiftLeft|ShiftRight)$/.test(e.code)&&mode==='ground'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){keyset.add(e.code);e.preventDefault()}});window.addEventListener('keyup',e=>keyset.delete(e.code));window.addEventListener('blur',()=>{keyset.clear();resetJoystick()});for(const b of document.querySelectorAll('[data-move]')){const k={forward:'ArrowUp',back:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[b.dataset.move];b.addEventListener('pointerdown',e=>{keyset.add(k);b.setPointerCapture(e.pointerId);e.preventDefault()});for(const ev of ['pointerup','pointercancel'])b.addEventListener(ev,()=>keyset.delete(k))}
function moveGround(dt){
 if(mode!=='ground'||(!keyset.size&&Math.abs(joyX)<.06&&Math.abs(joyY)<.06))return;
 let changed=false;
 const turn=(keyset.has('ArrowRight')?1:0)-(keyset.has('ArrowLeft')?1:0)+(Math.abs(joyX)>.06?joyX:0);
 if(turn){yaw+=turn*dt*1.05;changed=true}
 const lookUp=(keyset.has('KeyE')?1:0)-(keyset.has('KeyD')?1:0);
 if(lookUp){pitch=clamp(pitch+lookUp*dt*.9,THREE.MathUtils.degToRad(-70),THREE.MathUtils.degToRad(70));changed=true}
 const vertical=(keyset.has('KeyW')?1:0)-(keyset.has('KeyS')?1:0);
 if(vertical){const faster=keyset.has('ShiftLeft')||keyset.has('ShiftRight');viewerHeight=clamp(viewerHeight+vertical*dt*(14+Math.sqrt(viewerHeight)*1.5)*(faster?3:1),1.7,500);changed=true}
 let forward=(keyset.has('ArrowUp')?1:0)-(keyset.has('ArrowDown')?1:0)-(Math.abs(joyY)>.06?joyY:0);

 if(forward){
  const speed=walkSpeeds[walkSpeedIndex]*dt*forward,dx=Math.sin(yaw)*speed,dz=-Math.cos(yaw)*speed;
  const nextX=clamp(camera.position.x+dx,O.eMin-originE,O.eMin+outerWidth-originE),nextZ=clamp(camera.position.z+dz,originN-O.nMax,originN-(O.nMax-outerDepth));
  {
   camera.position.x=nextX;camera.position.z=nextZ;observer.e=originE+nextX;observer.n=originN-nextZ;
   updateTerrainDetail(observer.e,observer.n);scenery.updateLocalTrees(observer.e,observer.n);obsMarker.position.set(nextX,height(observer.e,observer.n)+3,nextZ);
   el('coords').textContent=`E ${Math.round(observer.e)} · N ${Math.round(observer.n)}`;
   updateAcousticMetrics();
   const fx=(observer.e-extent.eMin)/(extent.eMax-extent.eMin),fy=(extent.nMax-observer.n)/(extent.nMax-extent.nMin);
   if(osmActive){const q=osmMap.latLngToContainerPoint(observerLatLng()),size=osmMap.getSize();if(q.x<size.x*.12||q.x>size.x*.88||q.y<size.y*.12||q.y>size.y*.88)osmMap.panTo(observerLatLng(),{animate:false})}
   else if(fx<.12||fx>.88||fy<.12||fy>.88){centerMapOnObserver();drawMap()}
   if(performance.now()-lastMapRefresh>30){drawObserverMarker();lastMapRefresh=performance.now()}
  }
  changed=true;
 }
 if(changed){camera.position.y=walkingHeight(originE+camera.position.x,originN-camera.position.z);updateCameraView()}
}
function refreshRoutePicker(){const picker=el('routeSelect');picker.replaceChildren();routeSets.forEach((route,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=route.name;picker.append(option)});picker.value=String(activeRouteIndex);el('routeName').value=routeSets[activeRouteIndex].name}
function routeStatus(){
 const count=routePoints.length,active=!!routePlayback;
 el('routeToggle').textContent=routeMode?'✕ Kamera-ajo':'Kamera-ajo';
 el('routePlay').disabled=count<2||active;el('routeStop').disabled=!active;
 el('routeSavePoint').disabled=selectedRoutePoint<0||active;el('routeUndo').disabled=selectedRoutePoint<0||active;el('routeClear').disabled=activeRouteIndex<presetRoutes.length||active;
 el('routeAdd').disabled=count>=100||active;el('routeNew').disabled=routeSets.length>=24||active;
 el('routeStatus').textContent=active?`Toistetaan: piste ${routePlayback.leg+1} → ${routePlayback.leg+2}`:selectedRoutePoint>=0?`Piste ${selectedRoutePoint+1}/${count} valittu · säädä kameraa ja paina Tallenna piste.`:count<2?'Lisää vähintään kaksi pistettä omaan reittiin.':`${count} pistettä · valitse kartasta piste tai paina Toista.`
}
function storeRoute(){try{localStorage.setItem(routeStorageKey,JSON.stringify({routes:routeSets,active:activeRouteIndex}))}catch{}drawMap();drawRouteLeaflet();routeStatus()}
function stopRoute(){routePlayback=null;routeStatus()}
function selectRoutePoint(index){if(!routeMode||index<0||index>=routePoints.length)return;if(routePlayback)stopRoute();selectedRoutePoint=index;routePose(routePoints[index]);drawMap();drawRouteLeaflet();routeStatus()}
function cameraRoutePoint(){return{e:observer.e,n:observer.n,height:viewerHeight,yaw,pitch,fov:Number(el('fov').value)}}
el('routeToggle').onclick=()=>{routeMode=!routeMode;if(!routeMode&&routePlayback)stopRoute();el('routePanel').hidden=!routeMode;el('routeToggle').setAttribute('aria-expanded',String(routeMode));document.body.classList.toggle('routeMode',routeMode);drawMap();drawRouteLeaflet();routeStatus()};
el('routeSelect').onchange=event=>{if(routePlayback)stopRoute();activeRouteIndex=clamp(Number(event.target.value)||0,0,routeSets.length-1);routePoints=routeSets[activeRouteIndex].points;selectedRoutePoint=-1;refreshRoutePicker();storeRoute()};
el('routeNew').onclick=()=>{if(routeSets.length>=24)return;if(routePlayback)stopRoute();routeSets.push({name:`Oma reitti ${routeSets.length+1}`,points:[]});activeRouteIndex=routeSets.length-1;routePoints=routeSets[activeRouteIndex].points;selectedRoutePoint=-1;refreshRoutePicker();storeRoute()};
el('routeName').onchange=event=>{routeSets[activeRouteIndex].name=event.target.value.trim().slice(0,60)||`Reitti ${activeRouteIndex+1}`;refreshRoutePicker();storeRoute()};
el('routeAdd').onclick=()=>{if(routePlayback)stopRoute();if(routePoints.length>=100)return;routePoints.push(cameraRoutePoint());selectedRoutePoint=routePoints.length-1;storeRoute()};
el('routeSavePoint').onclick=()=>{if(selectedRoutePoint<0||routePlayback)return;routePoints[selectedRoutePoint]=cameraRoutePoint();storeRoute()};
el('routeUndo').onclick=()=>{if(selectedRoutePoint<0||routePlayback)return;routePoints.splice(selectedRoutePoint,1);selectedRoutePoint=-1;storeRoute()};
el('routeClear').onclick=()=>{if(activeRouteIndex<presetRoutes.length||routePlayback)return;routeSets.splice(activeRouteIndex,1);activeRouteIndex=Math.min(activeRouteIndex,routeSets.length-1);routePoints=routeSets[activeRouteIndex].points;selectedRoutePoint=-1;refreshRoutePicker();storeRoute()};
function routePose(p){
 observer.e=clamp(p.e,O.eMin+5,O.eMin+outerWidth-5);observer.n=clamp(p.n,O.nMax-outerDepth+5,O.nMax-5);viewerHeight=clamp(p.height,1.7,500);yaw=p.yaw;pitch=clamp(p.pitch,-1.25,1.25);
 el('fov').value=String(clamp(p.fov,5,90));el('fovText').textContent=`${Math.round(p.fov)}°`;setFieldOfView();
 updateTerrainDetail(observer.e,observer.n);const point=local(observer.e,observer.n);camera.position.set(point.x,walkingHeight(observer.e,observer.n),point.z);obsMarker.position.set(point.x,height(observer.e,observer.n)+3,point.z);
 scenery.updateLocalTrees(observer.e,observer.n);el('coords').textContent=`E ${Math.round(observer.e)} · N ${Math.round(observer.n)}`;updateCameraView();
 const fx=(observer.e-extent.eMin)/(extent.eMax-extent.eMin),fy=(extent.nMax-observer.n)/(extent.nMax-extent.nMin);
 if(osmActive){const q=osmMap.latLngToContainerPoint(observerLatLng()),size=osmMap.getSize();if(q.x<size.x*.12||q.x>size.x*.88||q.y<size.y*.12||q.y>size.y*.88)osmMap.panTo(observerLatLng(),{animate:false})}
 else if(fx<.12||fx>.88||fy<.12||fy>.88)centerMapOnObserver();
 if(performance.now()-lastMapRefresh>90){drawMap();lastMapRefresh=performance.now()}
}
function routeAngle(a,b,t){return a+Math.atan2(Math.sin(b-a),Math.cos(b-a))*t}
function advanceRoute(dt){
 if(!routePlayback)return;const start=routePoints[routePlayback.leg],end=routePoints[routePlayback.leg+1];if(!end){stopRoute();return}
 const speed=Number(el('routeSpeed').value)||1,distance=Math.hypot(end.e-start.e,end.n-start.n),duration=clamp(distance/20,2,30)/speed;
 routePlayback.progress=Math.min(1,routePlayback.progress+dt/duration);const t=routePlayback.progress,u=t*t*(3-2*t);
 routePose({e:start.e+(end.e-start.e)*u,n:start.n+(end.n-start.n)*u,height:start.height+(end.height-start.height)*u,yaw:routeAngle(start.yaw,end.yaw,u),pitch:start.pitch+(end.pitch-start.pitch)*u,fov:start.fov+(end.fov-start.fov)*u});
 if(t>=1){routePlayback.leg++;routePlayback.progress=0;if(routePlayback.leg>=routePoints.length-1)stopRoute();else routeStatus()}
}
el('routePlay').onclick=()=>{if(routePoints.length<2)return;keyset.clear();resetJoystick();if(mode!=='ground')setGround();selectedRoutePoint=-1;routePlayback={leg:0,progress:0};routePose(routePoints[0]);drawMap();drawRouteLeaflet();routeStatus()};
el('routeStop').onclick=stopRoute;
refreshRoutePicker();routeStatus();
function resize(){const w=el('scene').clientWidth,h=el('scene').clientHeight;camera.aspect=w/h;setFieldOfView();renderer.setSize(w,h)}window.addEventListener('resize',()=>{resize();setDrawerWidth(Math.min(drawerWidth,window.innerWidth))});resize();startLeaflet();setGround();faceProjectCenter();applyProjectPhase();el('status').hidden=true;
let previous=performance.now(),playAcc=0,lastRender=0;function tick(now){requestAnimationFrame(tick);const dt=Math.min(.25,(now-previous)/1000);previous=now;for(const [i,t] of turbines.entries())if(projectPhase===1)t.rotor.rotation.z+=dt*(Number(el('windSpeed').value)/8)*(.45+i*.012);if(playing){playAcc+=dt*[18,36,72,180,360][Number(el('timeRate').value)];if(playAcc>=1){const step=Math.floor(playAcc);playAcc-=step;const absolute=timeMinutes+step,days=Math.floor(absolute/1440);timeMinutes=absolute%1440;if(days){const date=new Date(el('date').value+'T12:00:00');date.setDate(date.getDate()+days);el('date').value=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');syncYearDial()}updateSun()}}if(routePlayback)advanceRoute(dt);else moveGround(dt);lakeLife.update(dt,terrainSnow);updateAcousticMetrics();const nearWater=window.LANDCOVER.inWater(observer.e,observer.n)||window.LANDCOVER.inWater(observer.e+50,observer.n)||window.LANDCOVER.inWater(observer.e-50,observer.n)||window.LANDCOVER.inWater(observer.e,observer.n+50)||window.LANDCOVER.inWater(observer.e,observer.n-50);windAudio.update(acousticResult(),observer,yaw,Number(el('windSpeed').value),projectPhase,{canopyHeight:soundCanopy(observer.e,observer.n),nearWater});if(mode==='overview')controls.update();if(!renderLight||now-lastRender>=33){renderer.render(scene,camera);lastRender=now}}requestAnimationFrame(tick);
function syncYearDial(){const value=el('date').value||'2026-06-21',date=new Date(value+'T12:00:00'),start=new Date(date.getFullYear()+'-01-01T12:00:00'),day=Math.round((date-start)/86400000),days=new Date(date.getFullYear(),1,29).getMonth()===1?366:365,dial=el('yearDial');dial.style.setProperty('--year-angle',(30+day/days*360)+'deg');dial.setAttribute('aria-valuemax',String(days));dial.setAttribute('aria-valuenow',String(day+1));dial.setAttribute('aria-valuetext',new Intl.DateTimeFormat('fi-FI',{dateStyle:'long'}).format(date));el('yearDialLabel').textContent=`${date.getDate()}.${date.getMonth()+1}.`}
function smooth(a,b,x){const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)}
function updateSeason(){const dateValue=el('date').value||'2026-06-21';if(dateValue===lastSeasonDate)return;lastSeasonDate=dateValue;const date=new Date(dateValue+'T12:00:00'),start=new Date(date.getFullYear()+'-01-01T12:00:00'),day=Math.round((date-start)/86400000);const snow=day<74?1:day<91?1-smooth(74,91,day):day>=334?smooth(334,345,day):0;const autumn=smooth(226,273,day),spring=smooth(91,151,day);const leafAmount=day<91?0:day<151?spring:day<226?1:day<273?1-smooth(248,273,day):0;scenery.setSeasonVisual({autumn,leafAmount,snow});terrainSnow=snow;terrainSpring=day>=91&&day<151?spring:1;for(const tile of terrainTiles.values())colorDetailTile(tile);for(let k=0;k<colors.length;k+=3){colors[k]=summerColors[k]*(1-snow)+.88*snow;colors[k+1]=summerColors[k+1]*(1-snow)+.91*snow;colors[k+2]=summerColors[k+2]*(1-snow)+.89*snow;if(snow<1&&day>=91&&day<151)colors[k+1]*=.78+.22*spring}geo.attributes.color.needsUpdate=true;el('date').setAttribute('aria-label',new Intl.DateTimeFormat('fi-FI',{dateStyle:'long'}).format(date))}
syncYearDial();updateSeason();
if(document.modelContext?.registerTool){void Promise.resolve(document.modelContext.registerTool({name:'set_niinimaki_view',title:'Aseta Niinimäen näkymä',description:'Aseta havaintopaikka ETRS-TM35FIN-koordinaateilla ja valitse näkymä.',inputSchema:{type:'object',properties:{e:{type:'number'},n:{type:'number'},ground:{type:'boolean'},date:{type:'string'},phase:{type:'integer',minimum:0,maximum:1}},required:['e','n'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute({e,n,ground,date,phase}){if(!Number.isFinite(e)||!Number.isFinite(n)||e<O.eMin||e>O.eMin+outerWidth||n<O.nMax-outerDepth||n>O.nMax)throw Error('Havaintopaikka on demokartan ulkopuolella.');setObserver(e,n);setGround();if(date){el('date').value=date;syncYearDial();updateSun()}if(Number.isInteger(phase)){projectPhase=phase>0?1:0;applyProjectPhase()}return{e:observer.e,n:observer.n,view:mode,date:el('date').value,phase:projectPhase}}})).catch(()=>{})}
})();
