const assert=require('node:assert/strict');
const model=require('../assets/acoustics.js');
const turbine={e:0,n:0};
const base={turbines:[turbine],terrain:()=>0,windFrom:270,windSpeed:8,temperature:15,humidity:.7,phase:1};
const at=(e,height=1.7,extra={})=>model.evaluate({...base,observer:{e,n:0,height},...extra});
const approx=(actual,wanted,tolerance=.02)=>assert.ok(Math.abs(actual-wanted)<tolerance,`${actual} != ${wanted}`);
const sourceSum=10*Math.log10(model.sourceBands.reduce((sum,db)=>sum+10**(db/10),0));
approx(sourceSum,107.8);
approx(model.airDbPerKm(63),.11,.02);
approx(model.airDbPerKm(125),.38,.03);
assert.ok(at(2000).level<at(1000).level-5,'distance should attenuate');
const twin=at(1000,1.7,{turbines:[turbine,{e:0,n:0}]});
approx(twin.level-at(1000).level,10*Math.log10(2));
assert.ok(at(1000,1.7,{windFrom:90}).level<at(1000).level-2,'upwind should reduce level');
const canopy=(e)=>e>850&&e<1000?28:0;
const inForest=at(1000,1.7,{canopy}),above=at(1000,35,{canopy}),open=at(1000);
assert.ok(inForest.sources[0].forestMetres>0,'forest intersects ear-level ray');
assert.equal(above.sources[0].forestMetres,0,'elevated ray clears canopy');
assert.ok(inForest.level<open.level,'forest provides some attenuation');
assert.ok(inForest.level>open.level-5,'forest does not mute the turbine');
const building=model.createBuildingIndex([{geometry:[[985,-8],[997,-8],[997,8],[985,8]],height:8}]);
const behind=at(1000,1.7,{building});
assert.ok(behind.sources[0].buildingScreen>0,'nearby cottage screens ray');
assert.ok(behind.level<open.level,'cottage reduces sound');
assert.ok(behind.level>open.level-12,'cottage does not mute low-frequency sound');
const acrossWater=at(1000,1.7,{water:e=>e>100&&e<900});
assert.ok(acrossWater.level>open.level,'water reflection modestly increases sound');
assert.ok(acrossWater.level<open.level+3,'water correction remains bounded');
const hill=at(1000,1.7,{terrain:e=>e>470&&e<530?130:0});
assert.ok(hill.level<open.level,'ridge screens path');
assert.ok(Number.isFinite(at(1000,1.7,{temperature:-15,humidity:.3}).level));
assert.equal(at(1000,1.7,{phase:0}).sources.length,0);
assert.equal(at(1000,1.7,{windSpeed:2}).level,-Infinity,'turbines stop below cut-in wind speed');
const detailed=at(1000,1.7,{bladeDetail:true});
approx(detailed.level,at(1000).level,1e-9);
assert.equal(detailed.sources[0].bladeHeightDb.lower.length,model.frequencies.length);
assert.ok(detailed.sources[0].bladePathDistance.upper>0,'blade-tip travel distance should change with source height');
console.log('Acoustic propagation checks passed');
